Feature/controller testing
ShinhyoBelok/PostPulse pull request #5
Opened 2023-04-04 20:04 UTC by ShinhyoBelok

# Changes 🛠️ 

- Add RSpec as a gem
- Create a Request spec file for all your controllers.
- Make sure that for each action check:
    - If response status was correct.
    - If a correct template was rendered.
    - If the response body includes correct placeholder text.

2023-04-04 20:43 UTC, vickymarz requested changes
Hi @ShinhyoBelok, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the Git Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 20:43 UTC, victorokoroji commented on spec/controllers/posts_controller_spec.rb
> +RSpec.describe UsersController, type: :request do
- [ ] Good job on your tests. It seems one of your tests is failing. Kindly fix it

![image](https://user-images.githubusercontent.com/63473584/229915584-825d06da-ec8e-4254-b960-00b21659f97a.png)

2023-04-04 22:29 UTC, ShinhyoBelok commented on spec/controllers/posts_controller_spec.rb
> +RSpec.describe UsersController, type: :request do
@vickymarz I tried rerunning the rspec and all got passed, I even deleted the repo and cloned it again and all the tests pass again.

2023-04-05 00:20 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @ShinhyoBelok, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 20:28 UTC, merged